# Lab 2: Linear Regression

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]]) # 1. 데이터 정의
y_train = torch.FloatTensor([[1], [2], [3]])
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [4]:
W = torch.zeros(1, requires_grad=True) #2. 학습에 필요한 W와 b의 값 초기화
print(W)
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [5]:
optimizer = optim.SGD([W,b], lr=0.01) #3. Pytorch를 이용해 optimizer 정의

$$ H(x) = Wx + b $$
$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $$

In [6]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = x_train * W + b  # r-1 . Hypothesis 예측
    cost = torch.mean((hypothesis - y_train) ** 2)  # r-2 . Cost 계산

    optimizer.zero_grad() # r-3 . Optimizer로 학습 (Gradient descent)
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1000 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100/1000 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200/1000 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300/1000 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400/1000 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500/1000 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600/1000 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700/1000 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800/1000 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900/1000 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000158


# High-level Implementation with nn.Module

In [7]:
class LinearRegressionModel(nn.Module):#nn.module을 inherit  (기능을 포함)
    def __init__(self): #사용할 layer 정의 ,실행 시 자동 호출
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x): #입력값, 출력값 계산
        return self.linear(x)

In [8]:
x_train = torch.FloatTensor([[1], [2], [3]]) #데이터 
y_train = torch.FloatTensor([[1], [2], [3]])

In [9]:
model = LinearRegressionModel() #모델 초기화
optimizer = optim.SGD(model.parameters(), lr=0.01) #optimizer 정의 

$$ H(x) = Wx + b $$
$$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $$

In [10]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train) # r-1. hypothesis 예측    
    cost = F.mse_loss(hypothesis, y_train) # r-2.cost 계산 (PyTorch의 mean squared error (MSE) 사용) 오차의 제곱의 평균
    
    optimizer.zero_grad() # r-3. Optimizer로 학습 (Gradient descent)
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))

Epoch    0/1000 W: 0.578, b: -0.413 Cost: 2.147149
Epoch  100/1000 W: 1.066, b: -0.150 Cost: 0.003239
Epoch  200/1000 W: 1.052, b: -0.118 Cost: 0.002002
Epoch  300/1000 W: 1.041, b: -0.093 Cost: 0.001237
Epoch  400/1000 W: 1.032, b: -0.073 Cost: 0.000764
Epoch  500/1000 W: 1.025, b: -0.057 Cost: 0.000472
Epoch  600/1000 W: 1.020, b: -0.045 Cost: 0.000292
Epoch  700/1000 W: 1.016, b: -0.035 Cost: 0.000180
Epoch  800/1000 W: 1.012, b: -0.028 Cost: 0.000111
Epoch  900/1000 W: 1.010, b: -0.022 Cost: 0.000069
Epoch 1000/1000 W: 1.008, b: -0.017 Cost: 0.000043
